from .address import AddressAreaRepository
from .area import AreaRepository
from .check_up import CheckUpRepository
from .check_up import CheckUpPlaceRepository
from .doctor import DoctorRepository
from .diagnosis import DiagnosisRepository
from .gender import GenderRepository
from .patient import PatientRepository
from .symptom import SymptomRepository