from .address import AddressService
from .area import AreaService
from .check_up import CheckUpService
from .diagnosis import DiagnosisService
from .doctor import DoctorService
from .gender import GenderService
from .patient import PatientService
from .symptom import SymptomService
from .check_up_place import CheckUpPlaceService