from .addres_area import AddressArea
from .area_doctor import AreaDoctor
from .area import Area
from .check_up_place import CheckUpPlace
from .check_up import CheckUp
from .diagnosis import Diagnosis
from .doctor import Doctor
from .gender import Gender
from .patient import Patient
from .symptom import Symptom
from .symptom_check_up import SymptomCheckUp